allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@iconify-json/lucide@1.2.123 || 1.2.142'
  - happy-dom@20.14.6
  - nuxt-auth-utils@0.5.31
